# 工作流的名称
name: Build and Push Docker Image to Docker Hub

# 触发工作流的事件
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:        # 允许手动触发

# 定义工作流中的任务
jobs:
  build-and-push:
    # 任务运行的虚拟环境
    runs-on: ubuntu-latest

    # 任务中的步骤
    steps:
      # 第一步：检出代码
      # 使用官方的 actions/checkout@v5 来获取你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v5

      # 第二步：登录到 Docker Hub
      # 使用官方的 docker/login-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第三步：设置 Docker Buildx
      # Buildx 是一个 Docker CLI 插件，可以实现更高级的构建功能
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第四步：构建并推送到 Docker Hub
      # 使用官方的 docker/build-push-action@v6
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # 使用当前目录作为构建上下文
          file: ./Dockerfile_whore_app  # !!! 重要：指定你的 Dockerfile 文件名
          push: true  # 设置为 true，表示要推送到仓库
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whore_app:latest, ${{ secrets.DOCKERHUB_USERNAME }}/whore_app:${{ github.sha }} # !!! 重要：设置镜像标签